#!/bin/bash

set -o -e pipefail

cd `dirname $0`
base_dir=`pwd`

yes | (
sudo apt-get update
sudo apt-get install wget --yes
sudo apt-get install sbcl --yes
sudo apt-get install clisp --yes
wget -O /tmp/ccl.tar.gz https://github.com/Clozure/ccl/releases/download/v1.11.5/ccl-1.11.5-linuxx86.tar.gz
)

yes | (
 cd /tmp
 tar -xzf ccl.tar.gz
)

export base_dir

$base_dir/test-on-implementation 'sbcl --script' .sbclrc
$base_dir/test-on-implementation clisp .clisprc.lisp
$base_dir/test-on-implementation "/tmp/ccl/lx86cl -e '(progn (load "run-tests.lisp") (ccl:quit))'" .ccl-init.lisp

