(format t "~%>>>>>>>>>>> Test program loading~%")
(load "init.lisp")
(format t "~%>>>>>>>>>>>>> Loaded init file~%")
(ql:quickload :asdf)
(push '*default-pathname-defaults* asdf:*central-registry*)
(ql:quickload :lisp-binary-test)
(format t "~%>>>>>>>> LISP-BINARY test system successfully loaded~%")

(lisp-binary-test::run-test)
#+sbcl (exit)
#+clisp (ext:exit)
#+ccl (ccl:quit)
