#!/bin/bash

set -x -e -o pipefail

cd `dirname $0`
base_dir=`pwd`

(yes || true) | (
sudo apt-get update
sudo apt-get install wget --yes
sudo apt-get install sbcl --yes
sudo apt-get install clisp --yes
wget -O $HOME/ccl.tar.gz https://github.com/Clozure/ccl/releases/download/v1.11.5/ccl-1.11.5-linuxx86.tar.gz
)



(yes || true) | (
 cd 
 tar -xzf ccl.tar.gz
 pwd
 ls -l
 ls -l ccl
 find . -name lx86cl
)

export base_dir

$base_dir/test-on-implementation clisp .clisprc.lisp &
$base_dir/test-on-implementation "$HOME/ccl/lx86cl64 -b -l" .ccl-init.lisp
$base_dir/test-on-implementation 'sbcl --script' .sbclrc

kill -2 $$
