#!/bin/bash

set -x -e -o pipefail

LISP="$1"
INIT=$HOME/"$2"

$base_dir/install-quicklisp "$LISP"

cp $INIT init.lisp
echo '>>>>>>>>>>>>>> RUNNING TEST'
(yes '' || true) | $LISP run-tests.lisp

rm -rf ~/quicklisp
rm -f init.lisp
rm -rf quicklisp.lisp
